# docker-compose.yml

version: "3.8"

services:
  api:
    build: ./api
    depends_on:
      - db
    ports:
      - 4000:4000
    env_file:
      - .env
    environment:
      - POSTGRES_HOST=db
      - POSTGRES_PORT=5432
    volumes:
      - ./api:/app
      
  db:
    image: postgres:14-alpine
    env_file:
      - .env
    ports:
      - 5432:5432
