# docker-compose.yml

version: "3.8"

services:
  api:
    build: ./api
    depends_on:
      - db
    ports:
      - 4000:4000
    env_file:
      - .env
    environment:
      - POSTGRES_HOST=db
      - POSTGRES_PORT=5432
    volumes:
      - ./api:/app
    networks:
      - api-network
      - db-network
      
  db:
    image: postgres:14-alpine
    env_file:
      - .env
    networks:
      - db-network

  web:
    build: ./front
    depends_on:
      - api
    ports:
      - 5173:5173
    environment:
      - VITE_BACK_URL=http://localhost:4000/api
    volumes:
      - ./front:/app
    networks:
      - api-network


networks:
  api-network:
  db-network:
